<a href="https://colab.research.google.com/github/haliskaric/FM-FIN/blob/main/DCF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [390]:
import requests 
import numpy as np
import pandas as pd

#Company you want
company = 'DIS'

#API key or key to get information
demo = '83c63f72c386e547c38ca988f6cbfd43'

#pulling income statement
IS = requests.get(f'https://financialmodelingprep.com/api/v3/income-statement/{company}?apikey={demo}').json()

#calculating revenue growth
revenue_g = (IS[0]['revenue'] - IS[1]['revenue']) / IS[1]['revenue']
#revenue_g = 0.10
print('The revenue growth of ' + company + ' is ' + str(revenue_g*100) + '%')

The revenue growth of DIS is 3.104545176484982%

In [391]:
net_income = IS[0]['netIncome']

BS = requests.get(f'https://financialmodelingprep.com/api/v3/balance-sheet-statement/{company}?apikey={demo}').json()

#Create table of the income statement
income_statement = pd.DataFrame.from_dict(IS[0], orient='index')

#splice the income statement only taking rows 5 - 26
income_statement = income_statement[5:36]

#change the name of the column from 0 to current year
income_statement.columns = ['current_year']

# create a new column with the values representing % change
income_statement['as_%_of_revenue'] = income_statement[3:36] / income_statement.iloc[3]

#creates new columns for each coming year. The equation takes this years revenue * the revenue growth rate. the last * is doing it for each row 
income_statement['next_year'] = (income_statement['current_year']['revenue'] * (1 + revenue_g)) * income_statement['as_%_of_revenue']
income_statement['next_2_year'] = (income_statement['next_year']['revenue'] * (1 + revenue_g)) * income_statement['as_%_of_revenue']
income_statement['next_3_year'] = (income_statement['next_2_year']['revenue'] * (1 + revenue_g)) * income_statement['as_%_of_revenue']
income_statement['next_4_year'] = (income_statement['next_3_year']['revenue'] * (1 + revenue_g)) * income_statement['as_%_of_revenue']
income_statement['next_5_year'] = (income_statement['next_4_year']['revenue'] * (1 + revenue_g)) * income_statement['as_%_of_revenue'] 

income_statement

,current_year,as_%_of_revenue,next_year,next_2_year,next_3_year,next_4_year,next_5_year
acceptedDate,2021-11-24 16:34:25,NaN,NaN,NaN,NaN,NaN,NaN
calendarYear,2021,NaN,NaN,NaN,NaN,NaN,NaN
period,FY,NaN,NaN,NaN,NaN,NaN,NaN
revenue,67418000000,1,"69,511,022,267","71,669,023,356","73,894,020,564","76,188,093,815","78,553,387,606"
costOfRevenue,45131000000,1,"46,532,112,284","47,976,722,731","49,466,181,762","51,001,881,722","52,585,258,181"
grossProfit,22287000000,0,"22,978,909,983","23,692,300,625","24,427,838,801","25,186,212,092","25,968,129,425"
grossProfitRatio,0,0,0,0,0,0,0
researchAndDevelopmentExpenses,0,0,0,0,0,0,0
generalAndAdministrativeExpenses,0,0,0,0,0,0,0
sellingAndMarketingExpenses,0,0,0,0,0,0,0
sellingGeneralAndAdministrativeExpenses,13517000000,0,"13,936,641,372","14,369,310,699","14,815,412,441","15,275,363,613","15,749,594,178"
otherExpenses,5111000000,0,"5,269,673,304","5,433,272,692","5,601,951,098","5,775,866,200","5,955,180,576"
operatingExpenses,18628000000,0,"19,206,314,675","19,802,583,391","20,417,363,539","21,051,229,814","21,704,774,753"
costAndExpenses,63759000000,1,"65,738,426,959","67,779,306,122","69,883,545,301","72,053,111,536","74,290,032,935"
interestIncome,140000000,0,"144,346,363","148,827,661","153,448,083","158,211,948","163,123,710"
interestExpense,1546000000,0,"1,593,996,268","1,643,482,603","1,694,505,263","1,747,111,944","1,801,351,824"
depreciationAndAmortization,5111000000,0,"5,269,673,304","5,433,272,692","5,601,951,098","5,775,866,200","5,955,180,576"
ebitda,8677000000,0,"8,946,381,385","9,224,125,837","9,510,492,990","9,805,750,542","10,110,174,497"
ebitdaratio,0,0,0,0,0,0,0
operatingIncome,3659000000,0,"3,772,595,308","3,889,717,234","4,010,475,262","4,134,982,279","4,263,354,672"
operatingIncomeRatio,0,0,0,0,0,0,0
totalOtherIncomeExpensesNet,-1098000000,-0,"-1,132,087,906","-1,167,234,087","-1,203,471,396","-1,240,833,709","-1,279,355,952"
incomeBeforeTax,2561000000,0,"2,640,507,402","2,722,483,147","2,807,003,866","2,894,148,570","2,983,998,719"
incomeBeforeTaxRatio,0,0,0,0,0,0,0
incomeTaxExpense,25000000,0,"25,776,136","26,576,368","27,401,443","28,252,134","29,129,234"
netIncome,1995000000,0,"2,056,935,676","2,120,794,174","2,186,635,187","2,254,520,264","2,324,512,864"
netIncomeRatio,0,0,0,0,0,0,0
eps,1,0,1,1,1,1,1
epsdiluted,1,0,1,1,1,1,1
weightedAverageShsOut,1818000000,0,"1,874,440,631","1,932,633,488","1,992,632,967","2,054,495,158","2,118,277,888"
weightedAverageShsOutDil,1830000000,0,"1,886,813,177","1,945,390,144","2,005,785,660","2,068,056,182","2,132,259,920"

In [392]:
balance_sheet = pd.DataFrame.from_dict(BS[0], orient='index')
balance_sheet = balance_sheet[8:-2]
balance_sheet.columns = ['current_year']

#balance sheet items as a % of revenue
balance_sheet['as_%_of_revenue'] = balance_sheet / income_statement['current_year'].iloc[3]

#creates new columns for each coming year. The equation takes this years revenue * the revenue growth rate. the last * is doing it for each row 
balance_sheet['next_year'] = income_statement['next_year']['revenue'] * balance_sheet['as_%_of_revenue']
balance_sheet['next_2_year'] = income_statement['next_2_year']['revenue'] * balance_sheet['as_%_of_revenue']
balance_sheet['next_3_year'] = income_statement['next_3_year']['revenue'] * balance_sheet['as_%_of_revenue']
balance_sheet['next_4_year'] = income_statement['next_4_year']['revenue'] * balance_sheet['as_%_of_revenue']
balance_sheet['next_5_year'] = income_statement['next_5_year']['revenue'] * balance_sheet['as_%_of_revenue']

balance_sheet

,current_year,as_%_of_revenue,next_year,next_2_year,next_3_year,next_4_year,next_5_year
cashAndCashEquivalents,15959000000,0,"16,454,454,365","16,965,290,334","17,491,985,437","18,035,032,027","18,594,937,744"
shortTermInvestments,0,0,0,0,0,0,0
cashAndShortTermInvestments,15959000000,0,"16,454,454,365","16,965,290,334","17,491,985,437","18,035,032,027","18,594,937,744"
netReceivables,13367000000,0,"13,781,984,554","14,209,852,490","14,651,003,781","15,105,850,812","15,574,818,774"
inventory,1331000000,0,"1,372,321,496","1,414,925,837","1,458,852,849","1,504,143,595","1,550,840,412"
otherCurrentAssets,3000000000,0,"3,093,136,355","3,189,164,171","3,288,173,213","3,390,256,036","3,495,508,066"
totalCurrentAssets,33657000000,0,"34,701,896,770","35,779,232,832","36,890,015,279","38,035,282,469","39,216,104,997"
propertyPlantEquipmentNet,32624000000,0,"33,636,826,818","34,681,097,303","35,757,787,636","36,867,904,308","38,012,485,052"
goodwill,78071000000,1,"80,494,749,465","82,993,745,327","85,570,323,644","88,226,892,999","90,965,936,750"
intangibleAssets,17115000000,0,"17,646,342,907","18,194,181,594","18,759,028,182","19,341,410,686","19,941,873,519"
goodwillAndIntangibleAssets,95186000000,1,"98,141,092,372","101,187,926,921","104,329,351,825","107,568,303,685","110,907,810,269"
longTermInvestments,3935000000,0,"4,057,163,853","4,183,120,337","4,312,987,198","4,446,885,834","4,584,941,414"
taxAssets,7246000000,0,"7,470,955,343","7,702,894,527","7,942,034,368","8,188,598,413","8,442,817,150"
otherNonCurrentAssets,30961000000,0,"31,922,198,232","32,913,237,298","33,935,043,618","34,988,572,378","36,074,808,414"
totalNonCurrentAssets,169952000000,3,"175,228,236,618","180,668,276,386","186,277,204,646","192,060,264,618","198,022,862,299"
otherAssets,0,0,0,0,0,0,0
totalAssets,203609000000,3,"209,930,133,388","216,447,509,218","223,167,219,926","230,095,547,087","237,238,967,296"
accountPayables,16357000000,0,"16,864,810,455","17,388,386,114","17,928,216,416","18,484,805,994","19,058,675,147"
shortTermDebt,5866000000,0,"6,048,112,620","6,235,879,009","6,429,474,690","6,629,080,636","6,834,883,439"
taxPayables,0,0,0,0,0,0,0
deferredRevenue,4317000000,0,"4,451,023,215","4,589,207,242","4,731,681,254","4,878,578,436","5,030,036,108"
otherCurrentLiabilities,4537000000,0,"4,677,853,215","4,823,079,281","4,972,813,956","5,127,197,212","5,286,373,366"
totalCurrentLiabilities,31077000000,0,"32,041,799,504","33,036,551,645","34,062,186,316","35,119,662,278","36,209,968,060"
longTermDebt,51769000000,1,"53,376,191,992","55,033,279,986","56,741,813,026","58,503,388,245","60,319,652,363"
deferredRevenueNonCurrent,7246000000,0,"7,470,955,343","7,702,894,527","7,942,034,368","8,188,598,413","8,442,817,150"
deferredTaxLiabilitiesNonCurrent,7246000000,0,"7,470,955,343","7,702,894,527","7,942,034,368","8,188,598,413","8,442,817,150"
otherNonCurrentLiabilities,13260000000,0,"13,671,662,690","14,096,105,635","14,533,725,603","14,984,931,680","15,450,145,653"
totalNonCurrentLiabilities,79521000000,1,"81,989,765,370","84,535,174,676","87,159,607,364","89,865,516,750","92,655,432,315"
otherLiabilities,0,0,0,0,0,0,0
capitalLeaseObligations,3229000000,0,"3,329,245,764","3,432,603,703","3,539,170,435","3,649,045,580","3,762,331,849"
totalLiabilities,110598000000,2,"114,031,564,874","117,571,726,321","121,221,793,680","124,985,179,028","128,865,400,375"
preferredStock,0,0,0,0,0,0,0
commonStock,55471000000,1,"57,193,122,255","58,968,708,573","60,799,418,771","62,686,964,194","64,633,109,317"
retainedEarnings,40429000000,1,"41,684,136,569","42,978,239,421","44,312,518,279","45,688,220,428","47,106,631,872"
accumulatedOtherComprehensiveIncomeLoss,-6440000000,-0,"-6,639,932,709","-6,846,072,420","-7,058,611,831","-7,277,749,624","-7,503,690,649"
othertotalStockholdersEquity,-907000000,-0,"-935,158,225","-964,190,634","-994,124,368","-1,024,987,408","-1,056,808,605"
totalStockholdersEquity,88553000000,1,"91,302,167,890","94,136,684,939","97,059,200,851","100,072,447,589","103,179,241,934"
totalLiabilitiesAndStockholdersEquity,199151000000,3,"205,333,732,764","211,708,411,261","218,280,994,531","225,057,626,618","232,044,642,309"
minorityInterest,4458000000,0,"4,596,400,624","4,739,097,958","4,886,225,395","5,037,920,470","5,194,324,987"
totalEquity,93011000000,1,"95,898,568,514","98,875,782,897","101,945,426,246","105,110,368,059","108,373,566,921"
totalLiabilitiesAndTotalEquity,203609000000,3,"209,930,133,388","216,447,509,218","223,167,219,926","230,095,547,087","237,238,967,296"
totalInvestments,0,0,0,0,0,0,0
totalDebt,57635000000,1,"59,424,304,612","61,269,158,995","63,171,287,715","65,132,468,881","67,154,535,802"
netDebt,41676000000,1,"42,969,850,248","44,303,868,661","45,679,302,278","47,097,436,854","48,559,598,058"

In [393]:
CF_forecast = {}
CF_forecast['next_year'] = {}
CF_forecast['next_year']['netIncome'] = income_statement['next_year']['netIncome']

CF_forecast['next_year']['inc_depreciation'] = income_statement['next_year']['depreciationAndAmortization']
CF_forecast['next_year']['inc_receivables'] = balance_sheet['next_year']['netReceivables'] - balance_sheet['current_year']['netReceivables']
CF_forecast['next_year']['inc_inventory'] = balance_sheet['next_year']['inventory'] - balance_sheet['current_year']['inventory']
CF_forecast['next_year']['inc_payables'] = balance_sheet['next_year']['accountPayables'] - balance_sheet['current_year']['accountPayables']
CF_forecast['next_year']['CF_operations'] = CF_forecast['next_year']['netIncome'] + CF_forecast['next_year']['inc_depreciation']
CF_forecast['next_year']['CAPEX'] = balance_sheet['next_year']['propertyPlantEquipmentNet'] - balance_sheet['current_year']['propertyPlantEquipmentNet']
CF_forecast['next_year']['FCF'] = CF_forecast['next_year']['CAPEX'] + CF_forecast['next_year']['CF_operations']

CF_forecast['next_2_year'] = {}
CF_forecast['next_2_year']['netIncome'] = income_statement['next_2_year']['netIncome']

CF_forecast['next_2_year']['inc_depreciation'] = income_statement['next_2_year']['depreciationAndAmortization']
CF_forecast['next_2_year']['inc_receivables'] = balance_sheet['next_2_year']['netReceivables'] - balance_sheet['next_year']['netReceivables']
CF_forecast['next_2_year']['inc_inventory'] = balance_sheet['next_2_year']['inventory'] - balance_sheet['next_year']['inventory']
CF_forecast['next_2_year']['inc_payables'] = balance_sheet['next_2_year']['accountPayables'] - balance_sheet['next_year']['accountPayables']
CF_forecast['next_2_year']['CF_operations'] = CF_forecast['next_2_year']['netIncome'] + CF_forecast['next_2_year']['inc_depreciation']
CF_forecast['next_2_year']['CAPEX'] = balance_sheet['next_2_year']['propertyPlantEquipmentNet'] - balance_sheet['next_year']['propertyPlantEquipmentNet']
CF_forecast['next_2_year']['FCF'] = CF_forecast['next_2_year']['CAPEX'] + CF_forecast['next_2_year']['CF_operations']

CF_forecast['next_3_year'] = {}
CF_forecast['next_3_year']['netIncome'] = income_statement['next_3_year']['netIncome']

CF_forecast['next_3_year']['inc_depreciation'] = income_statement['next_3_year']['depreciationAndAmortization']
CF_forecast['next_3_year']['inc_receivables'] = balance_sheet['next_3_year']['netReceivables'] - balance_sheet['next_2_year']['netReceivables']
CF_forecast['next_3_year']['inc_inventory'] = balance_sheet['next_3_year']['inventory'] - balance_sheet['next_2_year']['inventory']
CF_forecast['next_3_year']['inc_payables'] = balance_sheet['next_3_year']['accountPayables'] - balance_sheet['next_2_year']['accountPayables']
CF_forecast['next_3_year']['CF_operations'] = CF_forecast['next_3_year']['netIncome'] + CF_forecast['next_3_year']['inc_depreciation']
CF_forecast['next_3_year']['CAPEX'] = balance_sheet['next_3_year']['propertyPlantEquipmentNet'] - balance_sheet['next_2_year']['propertyPlantEquipmentNet']
CF_forecast['next_3_year']['FCF'] = CF_forecast['next_3_year']['CAPEX'] + CF_forecast['next_3_year']['CF_operations']

CF_forecast['next_4_year'] = {}
CF_forecast['next_4_year']['netIncome'] = income_statement['next_4_year']['netIncome']

CF_forecast['next_4_year']['inc_depreciation'] = income_statement['next_4_year']['depreciationAndAmortization']
CF_forecast['next_4_year']['inc_receivables'] = balance_sheet['next_4_year']['netReceivables'] - balance_sheet['next_3_year']['netReceivables']
CF_forecast['next_4_year']['inc_inventory'] = balance_sheet['next_4_year']['inventory'] - balance_sheet['next_3_year']['inventory']
CF_forecast['next_4_year']['inc_payables'] = balance_sheet['next_4_year']['accountPayables'] - balance_sheet['next_3_year']['accountPayables']
CF_forecast['next_4_year']['CF_operations'] = CF_forecast['next_4_year']['netIncome'] + CF_forecast['next_4_year']['inc_depreciation']
CF_forecast['next_4_year']['CAPEX'] = balance_sheet['next_4_year']['propertyPlantEquipmentNet'] - balance_sheet['next_3_year']['propertyPlantEquipmentNet']
CF_forecast['next_4_year']['FCF'] = CF_forecast['next_4_year']['CAPEX'] + CF_forecast['next_4_year']['CF_operations']

CF_forecast['next_5_year'] = {}
CF_forecast['next_5_year']['netIncome'] = income_statement['next_5_year']['netIncome']

CF_forecast['next_5_year']['inc_depreciation'] = income_statement['next_5_year']['depreciationAndAmortization']
CF_forecast['next_5_year']['inc_receivables'] = balance_sheet['next_5_year']['netReceivables'] - balance_sheet['next_4_year']['netReceivables']
CF_forecast['next_5_year']['inc_inventory'] = balance_sheet['next_5_year']['inventory'] - balance_sheet['next_4_year']['inventory']
CF_forecast['next_5_year']['inc_payables'] = balance_sheet['next_5_year']['accountPayables'] - balance_sheet['next_4_year']['accountPayables']
CF_forecast['next_5_year']['CF_operations'] = CF_forecast['next_5_year']['netIncome'] + CF_forecast['next_5_year']['inc_depreciation']
CF_forecast['next_5_year']['CAPEX'] = balance_sheet['next_5_year']['propertyPlantEquipmentNet'] - balance_sheet['next_4_year']['propertyPlantEquipmentNet']
CF_forecast['next_5_year']['FCF'] = CF_forecast['next_5_year']['CAPEX'] + CF_forecast['next_5_year']['CF_operations']

In [394]:
CF_forec = pd.DataFrame.from_dict(CF_forecast, orient='columns')

pd.options.display.float_format = '{:,.0f}'.format

CF_forec

,next_year,next_2_year,next_3_year,next_4_year,next_5_year
netIncome,"2,056,935,676","2,120,794,174","2,186,635,187","2,254,520,264","2,324,512,864"
inc_depreciation,"5,269,673,304","5,433,272,692","5,601,951,098","5,775,866,200","5,955,180,576"
inc_receivables,"414,984,554","427,867,937","441,151,290","454,847,031","468,967,963"
inc_inventory,"41,321,496","42,604,341","43,927,012","45,290,746","46,696,817"
inc_payables,"507,810,455","523,575,659","539,830,302","556,589,578","573,869,153"
CF_operations,"7,326,608,980","7,554,066,866","7,788,586,284","8,030,386,464","8,279,693,440"
CAPEX,"1,012,826,818","1,044,270,485","1,076,690,333","1,110,116,671","1,144,580,745"
FCF,"8,339,435,799","8,598,337,350","8,865,276,618","9,140,503,136","9,424,274,185"

In [395]:
#CALCULATING WACC

#WACC = Kd * (1-Tc) * (D/D+E) + Ke * (E/D+E)
#Kd = cost of debt
#Tc = tax effective rate
#Ke = cost of equity

import pandas_datareader.data as web
import datetime
import requests

#kd = RF + credit spread
# using interest coverage ratio to get cost of equity
def interest_coverage_and_RF(company):
  IS = requests.get(f'https://financialmodelingprep.com/api/v3/income-statement/{company}?apikey={demo}').json()
  EBIT = IS[0]['ebitda'] - IS[0]['depreciationAndAmortization']
  interest_expense = IS[0]['interestExpense']
  interest_coverage_ratio = EBIT / interest_expense

  #pulling the RF
  start = datetime.datetime(2021,3,17)
  end = datetime.datetime.today().strftime('%Y-%m-%d')
  Treasury = web.DataReader(['TB1YR'], 'fred', start, end)
  RF = float(Treasury.iloc[-1])
  RF = RF/100
  return [RF, interest_coverage_ratio]
  

interest_coverage_and_RF(company)

print('Risk free rate is ' + str(interest_coverage_and_RF(company)[0]*100) + '% and the interest coverage ratio of ' + company + ' is ' + str(interest_coverage_and_RF(company)[1]))

Risk free rate is 0.97% and the interest coverage ratio of DIS is 2.3065976714100906

In [396]:
#credit speads https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/ratings.htm see where interest coverage ratio lies and fill in the following
creditspread = 0.0378
RF = 0.0097
kd = RF + creditspread
print('cost of debt for ' + company + ' is ' + str((kd*100))+'%')

cost of debt for DIS is 4.75%

In [397]:
def costofequity(company):
  #RF
  start= datetime.datetime(2017, 3, 17)
  end = datetime.datetime.today().strftime('%Y-%m-%d')
  Treasury = web.DataReader(['TB1YR'], 'fred', start, end)
  RF = float(Treasury.iloc[-1])
  RF = RF/100

  #Beta
  beta = requests.get(f'https://financialmodelingprep.com/api/v3/company/profile/{company}?apikey={demo}')
  beta = beta.json()
  beta = float(beta['profile']['beta'])

  #market return
  start= datetime.datetime(2021, 3, 17)
  end = datetime.datetime.today().strftime('%Y-%m-%d')

  SP500 = web.DataReader(['sp500'], 'fred', start, end)
  SP500.dropna(inplace = True)

  SP500yearlyreturn = (SP500['sp500'].iloc[-1] / SP500['sp500'].iloc[-252])-1

  cost_of_equity = RF+(beta*(SP500yearlyreturn - RF))
  print(cost_of_equity)
  return cost_of_equity

ke = costofequity(company)
print('cost of equity of ' + company + ' is ' + str((ke*100))+'%')

0.1310328284080929
cost of equity of DIS is 13.10328284080929%

In [399]:
def wacc(company):
  FR = requests.get(f'https://financialmodelingprep.com/api/v3/ratios/{company}?apikey={demo}').json()
  ETR = FR[0]['effectiveTaxRate']

  #Cap structure
  BS = requests.get(f'https://financialmodelingprep.com/api/v3/balance-sheet-statement/{company}?period=quarer&apikey={demo}').json()
  Debt_to = BS[0]['totalDebt'] / (BS[0]['totalDebt'] + BS[0]['totalStockholdersEquity'])
  equity_to = BS[0]['totalStockholdersEquity'] / (BS[0]['totalDebt'] + BS[0]['totalStockholdersEquity'])

  #wacc
  WACC = (kd*(1-ETR)*Debt_to) + (ke* equity_to)
  print(WACC, equity_to, Debt_to)
  return WACC

RF_and_IntCov = interest_coverage_and_RF(company)
RF = RF_and_IntCov
interest_coverage_ratio = RF_and_IntCov[1]
ke = costofequity(company)
wacc_company = wacc(company)
print('wacc of ' + company + ' is ' + str(wacc_company*100) + '%')

0.1310328284080929
0.09791698366450119 0.6057473937669302 0.39425260623306974
wacc of DIS is 9.791698366450118%

In [400]:
!pip install numpy_financial 
import numpy_financial as npf


FCF_List = CF_forec.iloc[-1].values.tolist()
npv = npf.npv(wacc_company, FCF_List)
npv

Requirement already satisfied: numpy_financial in /usr/local/lib/python3.7/dist-packages (1.0.0)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from numpy_financial) (1.21.5)

36917890155.04347

In [401]:
LTGrowth = 0.02

Terminal_value = (CF_forecast['next_5_year']['FCF'] * (1+LTGrowth)) / (wacc_company - LTGrowth)
Terminal_value_Discounted = Terminal_value/(1+wacc_company)**5
Terminal_value_Discounted

77333637202.00806

In [402]:
target_equity_value = Terminal_value_Discounted + npv
debt = balance_sheet['current_year']['totalDebt']
target_value = target_equity_value - debt
target_value

number_of_shares = requests.get(f'https://financialmodelingprep.com/api/v3/enterprise-values/{company}?apikey={demo}').json()
number_of_shares = number_of_shares[0]['numberOfShares']

target_price_per_share = target_value / number_of_shares
target_price_per_share

31.14220426680502